name: linting_tool
description: A new Flutter project.

version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ^3.4.0-0

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  file_selector: ^1.0.0
  flutter_markdown: ^0.7.0
  google_fonts: ^6.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.2.1
  json2yaml: ^3.0.0
  json_annotation: ^4.8.1
  mockito: ^5.0.13
  provider: ^6.0.2
  yaml: ^3.1.0
  context_menus: ^2.0.0+1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  analysis_defaults:
    path: ../../analysis_defaults
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
